## Write a Numpy program to compute the multiplication of two given matrixes

In [1]:
import numpy as np
def mulMat(mat1,mat2):
    x1,y1=np.shape(mat1)
    x2,y2=np.shape(mat2)
    if y1==x2:
        result=np.dot(mat1,mat2)
        return result
    else:
        print("Dimensions doesn't match")


In [6]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])
mulMat(mat1,mat2)

array([[ 63, 320,  83],
       [ 77, 484, 102],
       [ 84, 248, 117]])

## Write a NumPy program to compute the determinant of a given square array

In [7]:
result=np.linalg.det([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
result

-9.51619735392994e-16

## Write a NumPy program to compute the cross product of two given vectors

In [10]:
v1 = [1, 2, 3]
v2 = [4, 5, 6]
np.cross(v1, v2)

array([-3,  6, -3])

## Write a NumPy program to compute the condition number of a given matrix

In [11]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.cond(a)

5.0522794445385096e+16

## Write a NumPy program to compute the inverse of a given matrix

In [12]:
np.linalg.inv(a)

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])